--for index, force in pairs(game.forces) do
  --if force.technologies["automation-3"].researched then
    --force.recipes[tank-assembling-machine"].enabled = true
    --force.resettechnologies()
  --end
--end
