data:extend({
    {
        type = "string-setting",
        name = "main-surface",
        setting_type = "runtime-global",
        default_value = "nauvis",
        localised_name = "Main surfaces",
        localised_description = "Surfaces on which different layer can be generated by this mod. (different values separated by a comma)"
    }
})
